# Generated by Django 4.2.7 on 2023-11-04 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('In_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('In_amount', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
