# Generated by Django 4.2.7 on 2023-11-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_income_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='In_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
