# Generated by Django 4.2.7 on 2023-11-07 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_income_in_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Ex_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Ex_date', models.DateField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='In_date',
            field=models.DateField(auto_now=True),
        ),
    ]
