# Generated by Django 4.2.7 on 2023-11-09 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Ex_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Ex_date', models.DateField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('In_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('In_date', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
